# Generated by Django 4.2.2 on 2023-06-14 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.TextField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=256)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10, verbose_name=((0, 'Female'), (1, 'Male'), (2, 'Other')))),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=256)),
                ('price', models.IntegerField(default=0)),
                ('stocking_status', models.BooleanField(default=False)),
                ('unit', models.CharField(max_length=50)),
                ('rate', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True)),
                ('discount', models.FloatField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EStore.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=256)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TransferServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Shippings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_time', models.IntegerField(default=1)),
                ('shipper_name', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EStore.orders')),
                ('transfer_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EStore.transferservices')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EStore.items')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EStore.orders')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EStore.shops'),
        ),
    ]
