# Generated by Django 4.2.2 on 2023-06-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='shop_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
