# Generated by Django 4.2.2 on 2023-06-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0002_useradmin_remove_customuser_groups_custom_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAdmin',
            new_name='User',
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups_custom',
            field=models.ManyToManyField(related_query_name='customuser', to='auth.group'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions_custom',
            field=models.ManyToManyField(blank=True, related_query_name='customuser', to='auth.permission'),
        ),
    ]
