# Generated by Django 4.2.2 on 2023-06-19 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_useradmin_user_customuser_groups_custom_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
