# Generated by Django 4.2.2 on 2023-06-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0004_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups_custom',
            field=models.ManyToManyField(to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions_custom',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
    ]
